### ISSUE TITLE
Search highlight and cursor block blink have same color

### ISSUE THREAD

**Issue by lionelblonde** [bartekjaszczak/finale-nvim#1]
The search highlight color and cursor block blink color seem to be identical.
Consequence: placing the cursor on a highlighted search result makes the cursor disappear in the selection.
There is nothing in my config that alters the colors or cursor appart from the "finale" colorscheme.

I think it would be more legible to have different colors for these scopes. If that is the intended behavior though, then it is a "me-problem", and I will edit my config to change the color of the cursor manually, for example.

Thanks!

**Comment by bartekjaszczak** [comment]
Hi,

It makes sense. I don't see this because I've got the search highlights (`hlsearch`) disabled.

There are 3 colours used for the accents (including some key highlights): yellow, blue and pink. Currently the search highlight is yellow and substitute highlight is blue; I guess I could shift that and make search results highlight blue and substitute highlight pink, which would leave yellow for the cursor while also making it distinct on the highlighted search results. Would that work for you?

![image](https://github.com/user-attachments/assets/48e3fd31-2388-4480-90ef-97bbdab9e8be)

**Comment by lionelblonde** [comment]
Ah, I see.
The change in color you suggest would be amazing.
